search result mobile view change
Njong392/Abbreve pull request #195
Opened 2022-11-26 18:41 UTC by E-fais

Mobile view UI change.

2022-11-26 18:43 UTC, E-fais commented
![Abbreve - Google Chrome 26-11-2022 9 30 59 PM](https://user-images.githubusercontent.com/102040088/204104260-8d8a9a57-5973-4bca-9623-96abe80ed964.png)

2022-11-28 17:50 UTC, Njong392 commented
Looks great! I tried to fix a merge conflicts and broke one of the vercel deployment checks. I'll check it tomorrow. This is an amazing job you did though 💜 thank you!

2022-11-29 18:46 UTC, Njong392 commented
Okay, I fixed the failing check, but there is one more thing. There are some changes that were automatically made to the `package-lock.json` file and I would like for you to revert those.

You can check [here](https://gist.github.com/kumarsonsoff3/fbc6ecde519250a9f0a4d7ccc9993a1a) for why this happened, and how you can easily fix it.

2022-11-29 18:53 UTC, Njong392 commented
Noticing just now after fixing the bad check that your changes don't reflect on my browser tools. Perhaps you could sync your fork, pull recent changes from this main upstream, and see if anything went wrong.

![Screenshot from 2022-11-29 19-48-23](https://user-images.githubusercontent.com/81039882/204619951-1f81d443-ddac-4e29-b223-9c47455398a6.png)

2022-12-04 17:16 UTC, E-fais commented
okay , let me check.

2022-12-18 18:41 UTC, Njong392 commented
Hello @E-fais any updates on this?

2023-01-02 11:53 UTC, Njong392 requested changes

2023-01-02 11:53 UTC, Njong392 commented on src/components/form.jsx
> +            <div className="flex gap-2 md:lg:flex-none ">
I see that you added a `flex gap-2 md:lg:flex-none` here. The flex is applied only to the button, maybe that's why the change isn't working for me (?) The flex has to be somehow applied to the button and the search result.

Did the changes get applied to your browser though? It'll be cool if you add screenshots to the pull request.

2023-01-28 17:42 UTC, E-fais commented
Hey, I am really sorry. I was busy, i could not follow up...

2023-01-28 17:46 UTC, Njong392 commented
I think after seeing and merging #219 we can close this Pull request. What do u think?

2023-01-31 18:36 UTC, E-fais commented
Yes, let's close this. Sorry for not responding.

2023-01-31 18:36 UTC, closed without merging