gn.json is created with the appropriate format
Njong392/Abbreve pull request #231
Opened 2023-01-26 04:06 UTC by JyothiKumar03

created gn.json file with its full form used often

Closes #

### What new changes did you make? Tick all applicable boxes
- [  ] Added new abbreviation
- [ ] Fixed something in the source code
- [ ] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Description
Created a branch named jk_contribute
created gn.json in that branch with appropriate abbrevations
kindly review and merge my pr

###

2023-01-26 11:56 UTC, Njong392 requested changes
Thank you very much for contributing to abbreve. Please take a look at the tiny suggestion I made.

2023-01-26 11:56 UTC, Njong392 commented on public/server/db/gn.json
> +    "alternatives": "Get Naked(used by couples or while sexting)"
I don't think the explanation in brackets is necessary haha.
```suggestion
    "alternatives": "Get Naked"
```

2023-02-04 11:08 UTC, Njong392 commented
Hello there. Do you need help updating this pull request?

2023-02-04 18:16 UTC, JyothiKumar03 commented
Hey Njong!!
I was busy with the exams and I totally forgot about my pending pr's!! My
apologies! I have removed the explanation part and created a new pr!!
Hope its good to go!!

On Sat, 4 Feb 2023 at 16:39, Njong Emy ***@***.***> wrote:

> Hello there. Do you need help updating this pull request?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Njong392/Abbreve/pull/231#issuecomment-1416724268>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU7XOMVNUUB6WE3M627R3LTWVY2FLANCNFSM6AAAAAAUHCEESY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-06 10:16 UTC, Njong392 commented
I believe this PR was a duplicate of #240 so I am going to close it.

2023-02-06 10:16 UTC, closed without merging