commited file with suggested changes
Njong392/Abbreve pull request #240
Opened 2023-02-04 18:14 UTC by JyothiKumar03

removed the brackets content

Closes #

### What new changes did you make? Tick all applicable boxes
- [ X] Added new abbreviation
- [ ] Fixed something in the source code
- [ ] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Describe the new changes you added.
I removed the extra content in the brackets. Sorry I was busy with the exams. 
Hope this one is good to go!!

### Share a screenshot of new changes

2023-02-04 22:37 UTC, Njong392 requested changes
Thanks for the new changes. Just one last suggested change and we are good to go. 

You don't need to create a new pull request if a current one needs adjustment. You can update the file as you normally would, commit, and push the changes, and GitHub will update this pull request for you.

2023-02-04 22:37 UTC, Njong392 commented on public/server/db/gn.json
> +  "alternatives": "Get Naked
You missed a quote at the end here.
```suggestion
  "alternatives": "Get Naked"
```

2023-02-05 12:05 UTC, JyothiKumar03 commented
Hey, I updated the file. Check if it requires any changes and merge it

2023-02-06 10:15 UTC, Njong392 approved these changes
This looks awesome now! Thank you so much for the new addition.

2023-02-06 10:15 UTC, merged