Added new "cul8r " slang to the data base
Njong392/Abbreve pull request #245
Opened 2023-02-07 13:25 UTC by JasonDsouza212

Closes #244

### What new changes did you make? Tick all applicable boxes
- [ ✓] Added new abbreviation
- [ ] Fixed something in the source code
- [ ] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Describe the new changes you added.
Added a new slang **cul8r** which means See You Later

2023-02-08 07:15 UTC, Njong392 requested changes
Thank you for the changes, but I see that you have made changes to the `package-lock.json` file. To revert this, please check out [this guide](https://gist.github.com/kumarsonsoff3/fbc6ecde519250a9f0a4d7ccc9993a1a).

To avoid this, instead of running `npm install` to install dependencies for this project, use `npm ci` as stated and referenced in the README.

2023-02-08 07:15 UTC, Njong392 commented on public/server/db.json
> +  },
You didn't need to add this to the `db.json` anymore.

2023-02-08 07:15 UTC, Njong392 commented on public/server/db/cul8r.json
> +  "definition": "See You Later"
This here looks amazing!

2023-02-08 10:54 UTC, JasonDsouza212 commented
I reverted the **package-lock.json** and even removed cul8r from **db.json** . I hope everything seems fine now

2023-02-09 18:06 UTC, Njong392 approved these changes
Perfect! Thank you so much for the contribution 💟

2023-02-09 18:06 UTC, merged