DOCS: Adding Abbrivation
Njong392/Abbreve pull request #247
Opened 2023-02-08 05:23 UTC by bobbyy16

Closes #

### What new changes did you make? Tick all applicable boxes
- [ ] Added new abbreviation
- [ ] Fixed something in the source code
- [ ] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Describe the new changes you added.

### Share a screenshot of new changes

2023-02-08 07:24 UTC, Njong392 requested changes
Thank you so much for the stellar addition! Please check out some of the changes I have proposed.

2023-02-08 07:24 UTC, Njong392 commented on public/server/db.json
> +  "bf": {
You didn't need to additionally add this to `db.json`. We no longer use this file to store abbreviations.

2023-02-08 07:24 UTC, Njong392 commented on public/server/db/bf.json
> +  "definition": "Boy Friend"
In the other file, you added an alternatives field. But you left that out here. Would you like to add that before I merge this in?
```suggestion
  "definition": "Boy Friend",
  "alternatives": "Breakfast"
```

2023-02-08 11:24 UTC, bobbyy16 commented
hey @Njong392 didn't see that one, commited alternative now, thanks for the help

2023-02-09 18:01 UTC, Njong392 approved these changes
Stellar addition! Thank you so much for the new addition. 🎉 

The word boyfriend, however, is one word. Sorry for not picking that tiny detail up.

2023-02-09 18:02 UTC, merged