Create Ijgb.json
Njong392/Abbreve pull request #409
Opened 2024-01-12 16:09 UTC by DICKSON-ENEH

Closes #

### What new changes did you make? Tick all applicable boxes
- [ ] Added new abbreviation
- [ ] Fixed something in the source code
- [ ] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Describe the new changes you added.

### Share a screenshot of new changes

2024-01-18 11:05 UTC, DICKSON-ENEH commented
i added a new abbreviation

2024-01-25 02:09 UTC, Njong392 requested changes
The file name is `Ijgb` but the abbreviation is something else. Would you mind rectifying that?

2024-01-29 00:24 UTC, Njong392 requested changes

2024-01-29 00:24 UTC, Njong392 commented on public/server/db/Ijgb.json
> +  "definition": "I just got back"
This should be written as "I Just Got Back" with the first letter of each word in caps like the README says.
```suggestion
  "definition": "I Just Got Back"
```

2024-07-06 04:29 UTC, closed without merging