chore: create a comprehensive contribution guideline for Abbreve.
Njong392/Abbreve pull request #96
Opened 2022-10-06 17:08 UTC by slim-codes

* This document specifies the rules and requirements for making contributions to this project.

* Along with step-by-step instructions for **setting up the project** and **making contributions** (Issues, PR's etc)

* These instructions are tailored for potential contributors with little or no experience in making OS contributions. 
Therefore, the instructions may be a bit verbose but comprehensive.

## Fixes Issue

Closes #4 

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers
@Njong392 
- I have highlighted 2 sections which require your attention.
- Firstly, there are 2 instances where a link is required for reaching out to maintainers or joining the community if there's one.
I was thinking of using the [Discord link to EddieHub](https://discord.gg/s2PQs2mN). But I think it's best to use your own Discord community if you have one. Else we can scrap that for now (i.e discard the community links in the document) until a community is set up
- Secondly, the sponsor button in the **README** points to Eddie's sponsorship page. So, I used the same URL under the **Financial contribution** section.

- I have highlighted them to facilitate modification if required

2022-10-06 17:13 UTC, slim-codes reviewed
# Highlighted Issues

2022-10-06 17:13 UTC, slim-codes commented on CONTRIBUTING.md
> +- If you're not certain of the changes that you want to make, get in touch with us first!  You can [chat with us](Discord Link) or file an [issue](https://github.com/Njong392/Abbreve/issues).
Discord Link Suggestion

2022-10-06 17:13 UTC, slim-codes commented on CONTRIBUTING.md
> +If something is missing here, or you feel something is not well described, either directly open a PR or ask in one of the [Community platforms](Discord link or Discussions link if any).
Discord Link Suggestion

2022-10-06 17:13 UTC, slim-codes commented on CONTRIBUTING.md
> +[Become a sponsor through the GitHub Sponsors program](https://github.com/sponsors/eddiejaoude)
Financial Contribution Section

2022-10-07 10:42 UTC, Njong392 requested changes

2022-10-07 23:03 UTC, adropofilm approved these changes

2022-10-07 23:04 UTC, merged